language: java
sudo: false

# Get latest install-jdk.sh script
before_install:
- wget -P ./target/ https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
  - env: JDK_RELEASE='OracleJDK 8'
    jdk: oraclejdk8
  - env: JDK_RELEASE='OracleJDK 9'
    jdk: oraclejdk9
  - env: JDK_RELEASE='OracleJDK 10'
    jdk: oraclejdk10
  - env: JDK_RELEASE='OpenJDK 10'
    jdk: openjdk10
  # Java 11 "Oracle JDK" (not yet provided by Travis CI)
  - env: JDK='Oracle JDK 11'
    install: . ./target/install-jdk.sh -F 11 -L BCL

script:
  - ./gradlew check
  - java -jar javafmt-cli/build/libs/javafmt-cli-0.1.0-SNAPSHOT.jar --test .
